Removing test devices in travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -25,7 +25,26 @@ before_script:
   - android-update-sdk --components=sys-img-$ABI-$API --accept-licenses='android-sdk-license-[0-9a-f]{8}'
   - echo no | android create avd --force -n test -t $API --abi $ABI -c 100M
   - emulator -avd test -no-skin -no-window &
-  - android-wait-for-emulator
+  - set +e
+
+    bootanim=""
+    failcounter=0
+    timeout_in_sec=360
+
+    until [[ "$bootanim" =~ "stopped" ]]; do
+    bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &`
+    if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
+    || "$bootanim" =~ "running" ]]; then
+    let "failcounter += 1"
+    echo "Waiting for emulator to start"
+    if [[ $failcounter -gt timeout_in_sec ]]; then
+    echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
+    exit 1
+    fi
+    fi
+    sleep 1
+    done
+
   - adb shell input keyevent 82 &
 
 script:
